// eslint-disable-next-line import/no-anonymous-default-export
export default {
  products: [
    {
      _id: "01",
      name: "Slim Shirt",
      category: "Shirts",
      image: "https://m.media-amazon.com/images/I/41QMVD8X36L._AC_UY1100_.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "02",
      name: "Small Shirt",
      category: "Shirts",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvqZ0jl3--UxjVYKtx1WfLpi_L9IrmnVp6gycmmjP8rT6_VvSQwfF3GAre8a-ermvexKA&usqp=CAU",
      price: 60,
      brand: "Nike",
      rating: 4.2,
      numReviews: 10,
    },
    {
      _id: "03",
      name: "Big Shirt",
      category: "Shirts",
      image: "/images/D1.jpeg",
      price: 50,
      brand: "Nike",
      rating: 4.3,
      numReviews: 10,
    },
    {
      _id: "04",
      name: "Best Pants",
      category: "Pants",
      image: "/images/D1.jpeg",
      price: 70,
      brand: "Nike",
      rating: 4.6,
      numReviews: 10,
    },
    {
      _id: "0",
      name: "New Pants",
      category: "Pants",
      image: "/images/D1.jpeg",
      price: 70,
      brand: "Nike",
      rating: 4.1,
      numReviews: 10,
    },
  ],
};
